### PR TITLE
Add 'Contributing' section to `README.md`.

### PR DESCRIPTION
**Pull request by tillahoffmann**
I've added a 'Contributing' section to the README to outline the steps required to add a new dataset. The instructions are relatively detailed to ensure researchers both with and without prior `git` and GitHub experience can contribute data. Let me know if I've missed anything or if it's too verbose.

### CODE REVIEW

**Review by YWAN446 — COMMENTED** [review]
Hi @tillahoffmann , do we want to have a Liscense statement for the README.md? Do you have any recommendations for which Liscense we should have?
Also, do we need to have a trademark? For a previous research tool, my group at Emory did it. I could consult with the Office of Technology Transfer at Emory.

**Comment by tillahoffmann** [comment]
Regarding license, people often create a dedicated `LICENSE` file in the repository. E.g., [here](https://github.com/tensorflow/tensorflow/blob/master/LICENSE) is the one for tensorflow. Something like MIT, BSD-3, or CC-BY could be good options for our code here. What do you think of [these options](https://choosealicense.com)? We may have to think more carefully about the data itself, depending on where it came from.

Regarding trademark, I don't know if we need one unless there is a commercial interest? Could be interesting to hear from the Office for Technology Transfer.

**Comment by YWAN446** [comment]
I used the MIT License for the repository I created under CIDMATH.org. I briefly discussed the data sharing agreement issues with the Emory OTT but I could meet with them about the License and Trademark.

**Comment by tillahoffmann** [comment]
MIT sounds good. Would be great to learn more about what the OTT had to say about data sharing/licensing!

**Review by YWAN446 — APPROVED** [review]

**Comment by YWAN446** [comment]
@tillahoffmann I think we can merge this and close this issue.

**Pull request merged**
