### PR TITLE
Add Human Metadata to woelfel2020.yaml

### PR DESCRIPTION
**Pull request by WenfeiXiao**
Added subject metadata, including age and sex, from the Challenger combined dataset.
Structured the metadata by creating attributes under each participant.

### CODE REVIEW

**Comment by tillahoffmann** [comment]
This looks great!

I forgot where the demographic data is in the manuscript and couldn't find it in a brief search. Maybe we could add a sentence on where the demographics came from in the `description` field here?

https://github.com/shedding-hub/shedding-hub/blob/0604633d2cc57eb568e06af0ed9d66b0a8b6ff7c/data/woelfel2020.yaml#L4-L11

**Comment by WenfeiXiao** [comment]
> This looks great!
> 
> I forgot where the demographic data is in the manuscript and couldn't find it in a brief search. Maybe we could add a sentence on where the demographics came from in the `description` field here?
> 
> https://github.com/shedding-hub/shedding-hub/blob/0604633d2cc57eb568e06af0ed9d66b0a8b6ff7c/data/woelfel2020.yaml#L4-L11
> 
> **Edit**: I should've properly read your comment; it's from the Challenger dataset. Could be good to add a line for others?

Great point! I can add a sentence to the description to clarify. 

"The demographic data, including age and sex, are derived from the Challenger et al. BMC Medicine (2022) 20:25 https://doi.org/10.1186/s12916-021-02220-0 supplement combined dataset."

Would that work?

**Comment by tillahoffmann** [comment]
That sounds great!

**Review by tillahoffmann — APPROVED** [review]
Looks great, thank you! Let's wait for @YWAN446 to also have a look before we merge.

**Comment by YWAN446** [comment]
Great work, Fiona! While creating the data for Liu et al. (2024), I had some questions. Maybe we can discuss the additional attributes to be included, format decisions (e.g., Age), and the storage of raw data files and data standardization codes (on Github?) in our next meeting. We could merge this after that.

**Review by tillahoffmann — CHANGES_REQUESTED** [review]
I think we're ready to merge this after removing the `Arts2023Longitudional.yaml` file. The following commands should do the trick.

```bash
git reset HEAD~
```

You can then run the following to make sure your branch is up to date with the main branch and push the changes.

```bash
git remote update
git rebase origin/main
git push --force
```

**Review by tillahoffmann — APPROVED** [review]
Awesome, thank you! 🚀

**Pull request merged**
