### PR TITLE
Restructure to keep extraction scripts and datasets together.

### PR DESCRIPTION
**Pull request by tillahoffmann**
As discussed in Slack, this PR restructures the folders so the cleaned dataset, extraction scripts, and maybe raw data are all kept together in the same folder. This is really just renaming a bunch of files.

Copied from Slack:

> Regarding the raw data, we could update the directory structure to group together the raw data, data processing script/markdown file, and the processed data. E.g., something like this.
> 
> ```
> data/
>   liu2024longitudinal/
>     raw.csv  # the raw data in whatever format the raw data come in, could be multiple files
>     liu2024longitudinal.yaml  # the processed data, same name as folder for searchability
>     processing.md  # the markdown notebook to turn raw into processed data, whatever name may be appropriate
> ```
> That would make it easy to see how things fit together from raw to processed data. What do you think?

### CODE REVIEW

**Review by YWAN446 — COMMENTED** [review]
Thank you for reorganizing the directory. One small thing about naming the folder and files (I am not sure whether this is going to impact the future functions we want to use but I assume a standardized naming rule could be benefitial for students to follow). Do we want to make the following changes:
1. change "woelfel2020" to "woelfel2020virological";
2. change "natarajan2020" to "natarajan2020gastrointestinal";
3. change "Liu2024Longitudinal" to "liu2024longitudinal";
4. change "Arts2023Longitudinal" to "arts2023longitudinal".
So we can have the format "last name + year + first word of publication" and everything not capitalized.

**Comment by tillahoffmann** [comment]
Good idea, I'll update that.

**Comment by tillahoffmann** [comment]
Huh, looks like I didn't get some of the capitalization right. Will fix in a future PR.

**Comment by YWAN446** [comment]
It is fine. I am rebase my personal branch (with my name) and I can fix them.

**Pull request merged**
