### PR TITLE
Create shrestha2020distribution.yaml

### PR DESCRIPTION
**Pull request by WenfeiXiao**
This study evaluated the transmission potential of COVID-19 by examining viral load over time. Over six weeks, 230 healthcare personnel underwent 528 tests at the Cleveland Clinic. Cycle threshold (Ct) values were obtained using RT-PCR targeting the N gene, and viral loads were calculated. Data were obtained from the combined dataset in the supplementary materials of Challenger et al. BMC Medicine (2022) 20:25 (https://doi.org/10.1186/s12916-021-02220-0).

There is a discrepancy between the paper suggesting limit_of_detection as 20 gc/mL and Challenger combined dataset suggesting  limit_of_detection as 67.24 gc/mL .

### CODE REVIEW

**Review by tillahoffmann — APPROVED** [review]
This looks great, thank you! I've spot-checked a few of the summary statistics against the publication, e.g., the number of patients with a certain number of samples, mean age, sex distribution.

**Comment by YWAN446** [comment]
I think the Challenger paper used either CT value 40 or 41 as the limit of detection and 67.24 were back-calculated using those CT values. We should use the limit of detection reported in the original paper as 20 gc/mL.

**Comment by WenfeiXiao** [comment]
I think you're right! That sounds like a reasonable explanation. I’ve set the limit of detection at 20 gc/mL, as reported in the original paper.

**Review by YWAN446 — APPROVED** [review]
I also did some spot checking it looks good to me.

**Pull request merged**
